/*
 * QDMObject - DM object in the chain (QDMStream etc)
 * NOTES:
 * - Generated by mkclass
 * (C) ??-??-98 MarketGraph/RVG
 */

#include <qlib/dmstream.h>
#include <qlib/debug.h>
DEBUG_ENABLE

void DbgPrintParams(const DMparams *p,int indent=0);

/*********
* OBJECT *
*********/
QDMObject::QDMObject()
{
}
QDMObject::~QDMObject()
{
}
//void QDMObject::AddPoolParams(QDMBPool *pool)
void QDMObject::AddProducerParams(QDMBPool *pool)
{ qerr("QDMObject::AddProducerParams() virtual function called\n");
}
void QDMObject::AddConsumerParams(QDMBPool *pool)
{ qerr("QDMObject::AddConsumerParams() virtual function called\n");
}
void QDMObject::RegisterPool(QDMBPool *pool)
{}
void QDMObject::Start()
{}

int QDMObject::GetFD()
{ return 0;
}

